const NutritionDetails = [
  {
    image: require('../assets/lasagna.jpg'),
    name: 'lasagna',
    ingredients: [
      '1/2 lb dry lasagna noodles (requires 9 lasagna noodles - unbroken)',
      '15 ounces Ricotta cheese',
      '1 1/2 lb (24 ounces) Mozzarella cheese, grated or sliced',
      '1/4 lb (4 ounces) freshly grated Parmesan cheese',
    ],
    totalCalories: '3322',
    totalFat: '170g',
    saturatedFat: '106g',
    cholesterol: '724mg',
    sodium: '5796mg',
    totalCarbohydrate: '169.5g',
    totalSugars: '9g',
    dietaryFiber: '0g',
    protein: '276.4g',
    calcium: '7490mg',
    iron: '3mg',
    potassium: '1103mg',
    fatPercent: '172%',
    saturatedFatPercent: '186%',
    cholesterolPercent: '96%',
    sodiumPercent: '69%',
    totalCarbohydratePercent: '131%',
    fiberPercent: '97%',
  },
  {
    image: require('../assets/lasagna.jpg'),
    name: 'vegetable burger',
    ingredients: [
      '1/2 onion',
      '2 slices cheese slices',
      '1/2 tomato',
      'Lettuce, Iceberg',
      '2 burger buns',
      '1/4 cup corn',
      '1 carrot',
      '1 potato',
    ],
    totalCalories: '730',
    totalFat: '21.4g',
    saturatedFat: '11.9g',
    cholesterol: '59mg',
    sodium: '992mg',
    totalCarbohydrate: '105.6g',
    totalSugars: '17.6g',
    dietaryFiber: '14.2g',
    protein: '34.3g',
    calcium: '461mg',
    iron: '7mg',
    potassium: '301mg',
    fatPercent: '27%',
    saturatedFatPercent: '60%',
    cholesterolPercent: '20%',
    sodiumPercent: '43%',
    totalCarbohydratePercent: '38%',
    fiberPercent: '51%',
  },
  {
    image: require('../assets/lasagna.jpg'),
    name: 'Arrabiata pasta',
    ingredients: [
      '1/2 teaspoon oregano',
      '4 large tomato',
      '4 cup pasta penne',
      '2 teaspoon garlic',
      '4 leaves basil',
    ],
    totalCalories: '515',
    totalFat: '4.6g',
    saturatedFat: ' 0.7g',
    cholesterol: '94mg',
    sodium: '54mg',
    totalCarbohydrate: '101.8g',
    totalSugars: '19.3g',
    dietaryFiber: '9.2g',
    protein: '21.6g',
    calcium: '115mg',
    iron: '6mg',
    potassium: '1835mg',
    fatPercent: '6%',
    saturatedFatPercent: '3%',
    cholesterolPercent: '31%',
    sodiumPercent: '2%',
    totalCarbohydratePercent: '37%',
    fiberPercent: '33%',
  },
  {
    image: require('../assets/lasagna.jpg'),
    name: 'Homemade pizza',
    ingredients: [
      'low fat mozzarella cheese',
      '2 tablespoon pizza sauce',
      '2 1/4 teaspoon dry yeast',
      '4 cup bread flour',
      '50 gm tomato',
      '50 gm mushroom',
      '50 gm onion',
      '50 gm capsicum (green pepper)',
      '1 handful black olives',
      '1 jalapeno',
    ],
    totalCalories: '2113',
    totalFat: '18g',
    saturatedFat: '6.7g',
    cholesterol: '36mg',
    sodium: '630mg',
    totalCarbohydrate: '402.5g',
    totalSugars: '10.3g',
    dietaryFiber: '20.5g',
    protein: '74.8g',
    calcium: '555mg',
    iron: '28mg',
    potassium: '1415mg',
    fatPercent: '23%',
    saturatedFatPercent: '33%',
    cholesterolPercent: '12%',
    sodiumPercent: '27%',
    totalCarbohydratePercent: '146%',
    fiberPercent: '73%',
  },
];

export default NutritionDetails;
